using QPLC.Core;
using QPLC.PlcSimAdapter;

if (args.Length < 3)
{
    Console.WriteLine("Usage: QPLC.PlcSimAdapter <conf.qplc> <output.xml> <instanceName> [scansPerSecond]");
    Console.WriteLine("  conf.qplc    - QPLC hardware/IO configuration");
    Console.WriteLine("  output.xml   - ladder XML generated by 'qplc'");
    Console.WriteLine("  instanceName - PLCSIM Advanced virtual controller instance name");
    Console.WriteLine("  scansPerSecond (opt) - default 10 (must match the vPLC cycle)");
    return 1;
}

string confPath = args[0];
string xmlPath = args[1];
string instance = args[2];
int scansPerSecond = args.Length >= 4 && int.TryParse(args[3], out var sps) ? sps : 10;
int periodMs = Math.Max(10, 1000 / Math.Max(1, scansPerSecond));

if (!File.Exists(confPath)) { Console.Error.WriteLine($"conf.qplc not found: {confPath}"); return 1; }
if (!File.Exists(xmlPath)) { Console.Error.WriteLine($"ladder XML not found: {xmlPath}"); return 1; }

var config = ConfigParser.Parse(confPath);
var networks = LadderXmlParser.Parse(xmlPath);
var sim = new LadderSimulator(networks);

Console.WriteLine("== QPLC ↔ PLCSIM Advanced (HIL) ==");
Console.WriteLine($"  conf:     {confPath}");
Console.WriteLine($"  ladder:   {xmlPath}");
Console.WriteLine($"  instance: {instance}");
Console.WriteLine($"  rate:     {scansPerSecond} scans/s (period {periodMs} ms)");
Console.WriteLine();

using var hil = new PlcSimHil(config, sim);

int rc = PlcSimBridge.qplc_plcsim_init(null);
if (rc != PlcSimBridge.OK)
{
    Console.Error.WriteLine("Failed to initialize PLCSIM Advanced API: " + PlcSimBridge.LastErrorToText(rc));
    Console.Error.WriteLine("Is PLCSIM Advanced installed and its Runtime Manager running?");
    return 2;
}
Console.WriteLine("PLCSIM Advanced API initialized.");

rc = hil.Connect(instance);
if (rc != PlcSimBridge.OK)
{
    Console.Error.WriteLine($"Failed to connect to instance '{instance}': {PlcSimBridge.LastErrorToText(rc)}");
    Console.Error.WriteLine("Start the virtual PLC in PLCSIM Advanced (or TIA Portal) first.");
    PlcSimBridge.qplc_plcsim_shutdown();
    return 3;
}
Console.WriteLine($"Connected to virtual PLC '{instance}'.");

rc = hil.Run(1000);
if (rc != PlcSimBridge.OK)
{
    Console.Error.WriteLine($"Failed to start vPLC: {PlcSimBridge.LastErrorToText(rc)}");
    PlcSimBridge.qplc_plcsim_shutdown();
    return 4;
}
Console.WriteLine($"vPLC '{instance}' running — QPLC scans synced every {periodMs} ms. Press Ctrl+C to stop.");

Console.CancelKeyPress += (_, e) => { e.Cancel = true; Console.WriteLine("\nStopping…"); };

Console.WriteLine($"{"scan",6} {"t(ms)",8}  vPLC state");
try
{
    long scan = 0;
    using var timer = new PeriodicTimer(TimeSpan.FromMilliseconds(periodMs));
    while (await timer.WaitForNextTickAsync())
    {
        hil.RunOneScan();
        scan++;

        if (scan % Math.Max(1, scansPerSecond) == 0)
        {
            int running = PlcSimBridge.qplc_plcsim_is_running();
            string state = running == 1 ? "RUN" : "STOP";
            Console.WriteLine($"{scan,6} {sim.CurrentTime,8:F0}  {state}");
        }
    }
}
catch (OperationCanceledException)
{
    // Ctrl+C — graceful shutdown
}
finally
{
    hil.Stop(500);
}

Console.WriteLine("Bye.");
return 0;