<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>QPLCVisualSimulator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QPLC.Core\QPLC.Core.csproj" />
  </ItemGroup>

</Project>
